name: tests_in_flutter
description: Tests in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
