name: unitary_tests
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
